import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { candidates, jobs } from '../data/seed';
import type { Candidate, JobRole, Role, Stage, UiState, View } from '../types';
interface State { candidates: Candidate[]; jobs: JobRole[]; ui: UiState; }
const persisted = <T,>(key:string, fallback:T):T => { try { return JSON.parse(localStorage.getItem(key)||'') as T } catch { return fallback } };
const initialState: State = { candidates: persisted('cg_cands_v2', candidates), jobs: persisted('cg_jobs_v2', jobs), ui: {view:'dashboard',roleFilter:'',search:'',sidebarOpen:false,selectedCandidateId:null,editingCandidateId:null,selectedJobId:null,candidateModal:false,jobModal:false,dateRange:'30d',stageFilter:'',langFilter:'',sort:'newest',selectedIds:[],session:{user:'Ahmed Assimi',role:'Recruitment Admin',notifications:6,authenticated:true}} };
const slice = createSlice({name:'recruit',initialState,reducers:{
 setView:(s,a:PayloadAction<View>)=>{s.ui.view=a.payload;s.ui.roleFilter='';s.ui.sidebarOpen=false}, setRoleFilter:(s,a:PayloadAction<Role>)=>{s.ui.view='candidates';s.ui.roleFilter=a.payload;s.ui.sidebarOpen=false}, setSearch:(s,a:PayloadAction<string>)=>{s.ui.search=a.payload}, clearSearch:s=>{s.ui.search=''}, toggleSidebar:s=>{s.ui.sidebarOpen=!s.ui.sidebarOpen}, closeSidebar:s=>{s.ui.sidebarOpen=false},
 openCandidateModal:(s,a:PayloadAction<number|undefined>)=>{s.ui.editingCandidateId=a.payload??null;s.ui.candidateModal=true}, closeCandidateModal:s=>{s.ui.candidateModal=false;s.ui.editingCandidateId=null}, openJobModal:(s,a:PayloadAction<string|undefined>)=>{s.ui.selectedJobId=a.payload??null;s.ui.jobModal=true}, closeJobModal:s=>{s.ui.jobModal=false;s.ui.selectedJobId=null}, selectCandidate:(s,a:PayloadAction<number|null>)=>{s.ui.selectedCandidateId=a.payload},
 addCandidate:(s,a:PayloadAction<Candidate>)=>{s.candidates.unshift(a.payload)}, updateCandidate:(s,a:PayloadAction<Candidate>)=>{s.candidates=s.candidates.map(c=>c.id===a.payload.id?a.payload:c)}, deleteCandidate:(s,a:PayloadAction<number>)=>{s.candidates=s.candidates.filter(c=>c.id!==a.payload);s.ui.selectedCandidateId=null},
 setStage:(s,a:PayloadAction<{id:number;stage:Stage;note?:string}>)=>{const c=s.candidates.find(x=>x.id===a.payload.id); if(c){c.stage=a.payload.stage;c.updated=new Date().toLocaleDateString('en-GB');c.lastActivity=`Moved to ${a.payload.stage}`;c.stageHistory.push({stage:a.payload.stage,date:new Date().toLocaleDateString('en-GB'),note:a.payload.note||'Stage updated'});}},
 addJob:(s,a:PayloadAction<JobRole>)=>{s.jobs.unshift(a.payload)}, updateJob:(s,a:PayloadAction<JobRole>)=>{s.jobs=s.jobs.map(j=>j.id===a.payload.id?a.payload:j)}, deleteJob:(s,a:PayloadAction<string>)=>{s.jobs=s.jobs.filter(j=>j.id!==a.payload)},
 setDateRange:(s,a:PayloadAction<UiState['dateRange']>)=>{s.ui.dateRange=a.payload}, setStageFilter:(s,a:PayloadAction<''|Stage>)=>{s.ui.stageFilter=a.payload}, setLangFilter:(s,a:PayloadAction<string>)=>{s.ui.langFilter=a.payload}, setSort:(s,a:PayloadAction<UiState['sort']>)=>{s.ui.sort=a.payload}, resetFilters:s=>{s.ui.stageFilter='';s.ui.langFilter='';s.ui.sort='newest'}, toggleSelect:(s,a:PayloadAction<number>)=>{s.ui.selectedIds=s.ui.selectedIds.includes(a.payload)?s.ui.selectedIds.filter(id=>id!==a.payload):[...s.ui.selectedIds,a.payload]}, clearSelection:s=>{s.ui.selectedIds=[]}, bulkStage:(s,a:PayloadAction<Stage>)=>{s.candidates=s.candidates.map(c=>s.ui.selectedIds.includes(c.id)?{...c,stage:a.payload,lastActivity:`Bulk moved to ${a.payload}`}:c);s.ui.selectedIds=[]}, resetDemoData:s=>{s.candidates=candidates;s.jobs=jobs}
}});
export const actions = slice.actions; export default slice.reducer;
